version: '3.8'

services:
  frontend:
    build:
      context: ./front
    ports:
      - 4200:4200
    volumes:
      - ./front/src:/app/src
    command: ng serve --host 0.0.0.0 --poll 1000

  backend:
    build:
      context: ./back
    ports:
      - 5000:5000
    volumes:
      - ./back:/app